### ISSUE TITLE
Can I sort all my posts by the count of likes ?

### ISSUE THREAD

**Issue by nowshad-sust** [cybercog/laravel-likeable#14]

**Comment by antonkomarev** [comment]
@nowshad-sust one of the solutions: Perform a database query.

```php
public function articlesSortedDescByLikes()
{
     return \DB::table('article')
            ->selectRaw('article.*, like_counter.count')
            ->join('like_counter', 'like_counter.likeable_id', '=', 'article.id')
            ->orderBy('like_counter.count', 'desc')
            ->take(5)
            ->get();
}
```

**Note:** If you are using more than one **Likeable Model** you should extend your join request with `likeable_type` condition. 

// Updated from `select` to `selectRaw` method.

**Comment by nowshad-sust** [comment]
@a-komarev, thanks for your help. Yes, currently i'm using this solution. But, I just wanted to know if there exists any available method to do that without raw query.

**Comment by antonkomarev** [comment]
Unfortunately, no. Feel free to add it to the package as PR.

**Comment by antonkomarev** [comment]
@nowshad-sust You can update package to 2.2.0 and try the new Eloquent Scope:

```php
$top10Articles = Article::orderByLikesCount('desc')->take(10)->get();
```

**Comment by nowshad-sust** [comment]
@a-komarev what did you mean exactly by "try the new Eloquent Scope" ?

I tried this code and don't know why it gives an error. my model is Post instead of Article

> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'App\Post' in 'on clause' (SQL: select count(*) as aggregate from `posts` left join `like_counter` on `like_counter`.`likeable_id` = `posts`.`id` and `like_counter`.`likeable_type` = `App\Post`)


Previously I tried something like this to work -

```
$posts = Post::join('like_counter as counter',function($join)
                        {
                            $join->on('counter.likeable_id', 
                                        '=',
                                        'posts.id')
                                ->where('counter.type_id','like');
                        })
                       ->orderBy('counter.count', 'desc')
                       ->select('posts.*')
                       ->paginate(9);
```

One problem with this piece of code is that, it gives only the posts with likes/dislikes, not the other posts not having any like/dislikes.

**Comment by antonkomarev** [comment]
@nowshad-sust I've released v2.2.1 with fix.

**Comment by antonkomarev** [comment]
@nowshad-sust v2.2.2 released. Now posts without likes should be fetched as well.

**Comment by nowshad-sust** [comment]
@a-komarev still the same error
> SQLSTATE[42S22]: Column not found: 1054 Unknown column 'App\Post' in 'on clause' (SQL: select count(*) as aggregate from `posts` left join `like_counter` on `like_counter`.`likeable_id` = `posts`.`id` and `like_counter`.`likeable_type` = `App\Post`)

The problem is coming from the `App\Post`, the quote is doing something that's not right
`like_counter`.`likeable_type` = `App\Post` this considers `App\Post` as a column name may be. using that in single quote may help.

**Comment by antonkomarev** [comment]
@nowshad-sust Yes, but it is in place in v2.2.2: https://github.com/cybercog/laravel-likeable/commit/06c428bf2b6690da1bdd45d698ac25d2eb996aa1#diff-bd817001fc9516da109b1b0635140509R300

**Comment by nowshad-sust** [comment]
@a-komarev I've updated the package to v2.2.2 already, but still getting the same error.

**Comment by antonkomarev** [comment]
@nowshad-sust Thanks a lot! It looks like SQLite ignore some syntax errors. Released v2.2.3 with fix for MySQL and all other databases. Tested it on one of my projects and it works :}

**Comment by nowshad-sust** [comment]
@a-komarev thanks for solving the issue, but I've found another issue within this thing.
When one post is liked by one user, and disliked by another user, then the `orderByLikesCount()` gives duplicate entries which is not expected. Please fix this issue.

For now, I'm using distinct() as a way around
`Post::orderByLikesCount()->distinct()->get();`

But I've seen the code inside and found that for likes you haven't check the 'type_id' !

so, I guess you can add this line of code in the join condition to solve the issue 
`->where('like_counter.type_id', '=', 'like')`

**Comment by antonkomarev** [comment]
@nowshad-sust good catch! Initially I thought about sorting of the likeable entities by the average value of likes\dislikes. `Post` with `3 likes` and `5 dislikes` which has `-2 average likes value` should be positioned lower than `Post` with `2 likes` and `1 dislike` which has `1 average likes value`.

**Comment by nowshad-sust** [comment]
@a-komarev that was a good thought though! hope to see proper implementation from you.
But, for now - fixing this issue should be enough.

**Comment by antonkomarev** [comment]
@nowshad-sust PRs are always welcomed! :} https://github.com/cybercog/laravel-likeable/pull/17

**Comment by antonkomarev** [comment]
@nowshad-sust release `v2.2.4` fixes `orderByLikesCount`. Additionally `orderByDislikesCount` method was implemented.
